INFO     HTTP_LOGGER:event_hooks.py:27 Send POST request to http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:35 Got response: 200, reason: OK from http://localhost:8000/api/v1/users
INFO     HTTP_LOGGER:event_hooks.py:27 Send POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:35 Got response: 200, reason: OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_LOGGER:event_hooks.py:27 Send GET request to http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP_LOGGER:event_hooks.py:35 Got response: 422, reason: Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:19 Check that response status code equals 422
INFO     FILES_ASSERTIONS:files.py:144 Check create file with incorrect file id response
INFO     ERRORS_ASSERTIONS:errors.py:40 Check validation error response
INFO     BASE_ASSERTIONS:base.py:74 Check that "details's" length equals 1
INFO     ERRORS_ASSERTIONS:errors.py:19 Check validation error
INFO     BASE_ASSERTIONS:base.py:38 Check that "type" equals "uuid_parsing"
INFO     BASE_ASSERTIONS:base.py:38 Check that "input" equals "incorrect-file-id"
INFO     BASE_ASSERTIONS:base.py:38 Check that "context" equals "{'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}"
INFO     BASE_ASSERTIONS:base.py:38 Check that "message" equals "Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1"
INFO     BASE_ASSERTIONS:base.py:38 Check that "location" equals "['path', 'file_id']"
INFO     SCHEMA_ASSERTIONS:schema.py:20 Validate JSON schema